spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000  # 10 minutes
      max-lifetime: 1800000  # 30 minutes
security:
  jwt:
    secret-key:${JWT_SECRET}
    expiration-time:3600000
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none  # Or create, create-drop, validate as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:resources/db/changelog/db.changelog-master.yaml
    enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    liquibase: DEBUG
debug: true
